Configurizing email links
djangocon/2017.djangocon.us pull request #84
Opened 2017-03-23 23:58 UTC by KatherineMichel

2017-03-24 17:13 UTC, jefftriplett requested changes
Please see notes. 90% there and looking good!

2017-03-24 17:13 UTC, jefftriplett commented on CONTRIBUTING.md
> +As a contributor, you can help us keep the Django community open and inclusive. Please read and follow our [Code of Conduct](https://www.djangoproject.com/conduct/), and report unacceptable behavior
We might as well cover the 2nd `coc@djangocon.us` reference here too just to avoid confusion if we ever change the name in the future.

2017-03-24 17:13 UTC, jefftriplett commented on _includes/footer.html
> +          href="mailto:{{site.contact_us_email}}">hello@djangocon.us</a>
Ditto, suggestion about matching the 2nd hello@ reference to avoid conflicts if we change the address.

2017-03-24 17:13 UTC, jefftriplett commented on _pages/coc.md
> +**If you are being harassed**, notice that someone else is being harassed, or have any other concerns, please contact the Code of Conduct committee at DjangoCon US by emailing <a href="mailto:{{site.
Ditto, previous suggestion on `coc@djangocon.us` reference

2017-03-24 17:42 UTC, KatherineMichel commented
Hope that takes care of it.

2017-03-27 16:48 UTC, jefftriplett commented
Thank you! 👍

2017-03-27 16:48 UTC, merged